/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.dagpenger.inntekt

import mu.KotlinLogging
import no.nav.dagpenger.streams.Service
import org.apache.kafka.streams.KafkaStreams
import org.apache.kafka.streams.StreamsBuilder

private val LOGGER = KotlinLogging.logger {}

class Datalaster(val env: Environment) : Service() {
    override val SERVICE_APP_ID: String = "dagpenger-inntekt-datasamler"

    override fun setupStreams(): KafkaStreams {
        LOGGER.info { "Initiating start of $SERVICE_APP_ID" }
        val builder = StreamsBuilder()

        val inntektEvent = builder.stream<String, String>(
            "privat-dagpenger-inntekt-v1" //todo: topic name ??
        )

        inntektEvent.mapValues { key, value ->
            // fetch "inntekt" object from dp-inntekt-api
            // add "inntekt" to
        }.to("privat-dagpenger-inntekt-v1")

        return KafkaStreams(builder.build(), getConfig())
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            val datalaster = Datalaster(Environment())
            datalaster.start()
        }
    }
}
