/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.dagpenger.inntekt

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun hei() {
        assertNotNull("hei", "hei")
    }
}
